apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: crud-app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_DATABASE: "crud_operations"
  MYSQL_USER: "myuser"
  MYSQL_PASSWORD: "mypassword"
  DB_HOST: "mysql-svc"
  DB_USER: "myuser"
  DB_PASSWORD: "mypassword"
  DB_DATABASE: "crud_operations"
